//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL.Options
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_PRODUCT
    {
        public ms_PRODUCT()
        {
            this.SALES = new HashSet<ms_SALE>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public decimal VENDOR_ID { get; set; }
        public decimal MEASURE_ID { get; set; }
        public decimal CATEGORY_ID { get; set; }
        public decimal PRICE { get; set; }
    
        public virtual ms_CATEGORY CATEGORY { get; set; }
        public virtual ms_MEASURE MEASURE { get; set; }
        public virtual ms_VENDOR VENDOR { get; set; }
        public virtual ICollection<ms_SALE> SALES { get; set; }
    }
}
