//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL.Options
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MsSQLEntities : DbContext
    {
        public MsSQLEntities()
            : base("name=MsSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ms_CATEGORY> ms_CATEGORY { get; set; }
        public DbSet<ms_MEASURE> MEASURES { get; set; }
        public DbSet<ms_PRODUCT> PRODUCTS { get; set; }
        public DbSet<ms_SALE> SALES { get; set; }
        public DbSet<ms_VENDOR> VENDORS { get; set; }
    }
}
