//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL.Options
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_measure
    {
        public my_measure()
        {
            this.products = new HashSet<my_product>();
        }
    
        public int ID { get; set; }
        public string MEASURE_NAME { get; set; }
    
        public virtual ICollection<my_product> products { get; set; }
    }
}
