//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySQL.Options
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_product
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public int VENDOR_ID { get; set; }
        public int MEASURE_ID { get; set; }
        public int CATEGORY_ID { get; set; }
        public decimal PRICE { get; set; }
    
        public virtual my_category category { get; set; }
        public virtual my_measure measure { get; set; }
        public virtual my_vendor vendor { get; set; }
    }
}
