//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlSupermarketEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE
    {
        public int ID { get; set; }
        public decimal PRODUCT_ID { get; set; }
        public int QUANTITY { get; set; }
        public decimal UNIT_PRICE { get; set; }
        public string STORE_NAME { get; set; }
        public System.DateTime REPORT_DATE { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
