DROP DATABASE IF EXISTS supermarket;

CREATE DATABASE supermarket CHARACTER SET utf8 COLLATE utf8_general_ci;

USE supermarket;

CREATE TABLE category
(
	ID int AUTO_INCREMENT PRIMARY KEY,
	NAME nvarchar(100) NOT NULL
);

CREATE TABLE vendors
(
	ID int AUTO_INCREMENT PRIMARY KEY,
	VENDOR_NAME nvarchar(200) NOT NULL
);

CREATE TABLE measures
(
	ID int AUTO_INCREMENT PRIMARY KEY,
	MEASURE_NAME nvarchar(100) NOT NULL
);

CREATE TABLE products
(
	ID int AUTO_INCREMENT PRIMARY KEY,
	NAME nvarchar(100) NOT NULL,
	VENDOR_ID int NOT NULL,
	MEASURE_ID int NOT NULL,
	CATEGORY_ID int NOT NULL,
	PRICE decimal(19, 4) NOT NULL,
	FOREIGN KEY (VENDOR_ID) REFERENCES vendors(ID),
	FOREIGN KEY (MEASURE_ID) REFERENCES measures(ID),
	FOREIGN KEY (CATEGORY_ID) REFERENCES category(ID)	
);










